### ISSUE TITLE
Website link to template is dead

### ISSUE THREAD

**Issue by jamesdwalker** [Teradata/covalent-markdown-navigator-nightly#31]
On [the resources page on teradata.github.io](https://teradata.github.io/covalent/#/style-guide/resources), the Axure link sends me to `https://github.com/Teradata/covalent-resources/raw/develop/axure/covalent-axure.rplib`, `404` error (same for all 3 templates).

It should instead link to `https://raw.githubusercontent.com/Teradata/covalent-resources/develop/templates/axure/covalent-axure.rplib`

Links have changed due to https://github.com/Teradata/covalent-resources/pull/14

**Comment by jeremysmartt** [comment]
This was fixed with https://github.com/Teradata/covalent/pull/1399
